---

- name: '[system] Install default configurationa'
  template: src=vimrc.j2 dest={{ vim_root_config }} owner=root group=root mode=0644
  tags:
    - vim

- name: '[system] Install default plugins'
  template: src=vimrc.bundles.j2 dest={{ vim_root_bundles }} owner=root group=root mode=0644
  tags:
    - vim

- name: '[system] Install Vundle'
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: /var/lib/vim/addons/Vundle.vim
    version: "{{ vim_vundle_version }}"
  tags:
    - vim

- name: '[system] Downloads plugins'
  command: vim +PluginInstall +qal
  tags:
    - vim
