---

- include: install.yml

- include: configure_system.yml
  vars:
    vim_root_config: /etc/vim/vimrc.local
    vim_root_bundles: /etc/vim/vimrc.bundles
  when: vim_env == "system"

- include: configure_user.yml
  vars:
    vim_root_config: ~/.vimrc
    vim_root_bundles: ~/.vimrc.bundles
  when: vim_env == "user"
